global:
  scrape_interval: 5s # Scrape every 5 seconds

scrape_configs:
  - job_name: 'webapp'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7298']

  - job_name: 'identity-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:5243']