{
 "title": "User Authentication Flow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logged In Users",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "identity_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average User Session Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "identity_session_duration_seconds_sum / identity_session_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Users",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "identity_active_user_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Successfull Login Attempts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "identity_successful_logins_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Login Attempts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "identity_failed_logins_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Login Traces",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "operation": "UserLogin", "service": "identity-api" }
   ]
  },
  {
   "title": "Total Logins Attempts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "identity_login_event_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Identity Database Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "operation": "identitydb", "service": "identity-api" }
   ]
  },
  {
   "title": "Logout Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "operation": "UserLogout", "service": "identity-api" }
   ]
  },
  {
   "title": "Response Time",
   "type": "barchart",
   "description": "Response time taken from Identity-API traces.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "service": "identity-api" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "service": "identity-api" }
   ]
  }
 ]
}